version: "3"
services:
  ldapauthd:
    image: g0dscookie/ldapauthd
    ports:
      - 80:80
    environment:
      # Loglevel the daemon should run on.
      #- LDAPAUTHD_LOGLEVEL=INFO
      # User the daemon should be run with.
      #- LDAPAUTHD_USER=nobody
      # Umask the daemon should run with.
      #- LDAPAUTHD_UMASK=755
      # IP address the daemon should listen on.
      #- LDAPAUTHD_IP=0.0.0.0
      # Port the daemon should listen on.
      #- LDAPAUTHD_PORT=80
      # String to set in WWW-Authenticate
      #- LDAPAUTHD_REALM=Authorization required
      # Base DN every search request will be based on.
      #- LDAP_BASEDN=ou=Company,dc=example,dc=org
      # Bind user to use for querying your ldap server.
      #- LDAP_BINDDN=cn=bind user,dc=example,dc=org
      # Bind users password.
      # This can also be a path to a plain text file
      #- LDAP_BINDPW=password
      # Comma seperated list of ldap backend names.
      #- LDAP_BACKENDS=dc01
      # Hostname of your domain controller.
      #- LDAP_DC01_HOST=dc01.example.org
      # Port on your domain controller to connect to.
      #- LDAP_DC01_PORT=636
      # Use SSL for ldap connection.
      #- LDAP_DC01_SSL=True
      # Verify remote SSL certificate.
      #- LDAP_DC01_SSL_VALIDATE=True
